### PR TITLE
Automate Pypi update via CircleCI

### PR DESCRIPTION
**Pull request by FelixKleinpeter**
Modifications added to Makefile, setup.py. A config.yml has been add too.

### CODE REVIEW

**Comment by FelixKleinpeter** [comment]
Because of an issue I reported on my channel I couldn't finish this task. Merging is not necessary but for those who wants to finish this work, they can use modifications I did to the Makefile. I based my work on this article : https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/

**Comment by imadelh** [comment]
levlaz as username?? 
password also is there..

**Comment by FelixKleinpeter** [comment]
Oh yes I'm sorry. I should have deleted this branch, I just did some test but when I got stuck I stopped updating the code. I didn't got a lot of good results, I suggest you to restart from zero if you want to complete this task. I'm very sorry, don't hesitate asking me question about this! I'll do my best to help you.

**Comment by imadelh** [comment]
@FelixKleinpeter No worries, I was actually checking how you could use Pypi with CI. Anyway, as you suggested this task has to be restarted from zero. 
Thank you very much for your reply. Cheers

**Pull request closed without merging**
